apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  namespace: default
spec:
  selector:
    app: admin-frontend               
  ports:
    - name: http
      port: 3000                       
      targetPort: 3000               
  type: ClusterIP
