apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: appflowyinc/admin_frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: RUST_LOG
              value: info
            - name: ADMIN_FRONTEND_PATH_PREFIX
              value: "/console"
            - name: ADMIN_FRONTEND_REDIS_URL
              value: "redis://redis:6379"
            - name: ADMIN_FRONTEND_GOTRUE_URL
              value: "http://gotrue:9999"
            - name: ADMIN_FRONTEND_APPFLOWY_CLOUD_URL 
              value: "http://appflowy-cloud:8000"
            - name: ADMIN_FRONTEND_PORT
              value: "3000"
