apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appflowy-worker
  template:
    metadata:
      labels:
        app: appflowy-worker
    spec:
      containers:
        - name: appflowy-worker
          image: appflowyinc/appflowy_worker:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            # Non-sensitive environment variables
            - name: RUST_LOG
              value: info
            - name: APPFLOWY_ENVIRONMENT
              value: production
            - name: APPFLOWY_WORKER_ENVIRONMENT
              value: production
            - name: APPFLOWY_WORKER_IMPORT_TICK_INTERVAL
              value: "30"
            - name: APPFLOWY_S3_USE_MINIO
              value: "true"
            - name: APPFLOWY_S3_BUCKET
              value: appflowy
            - name: APPFLOWY_S3_REGION
              value: us-east-1
            
            # Sensitive data from secrets
            - name: APPFLOWY_WORKER_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_WORKER_REDIS_URL
            - name: APPFLOWY_WORKER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_WORKER_DATABASE_URL
            - name: APPFLOWY_WORKER_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_WORKER_DATABASE_NAME
            - name: APPFLOWY_S3_MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_S3_MINIO_URL
            - name: APPFLOWY_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_S3_ACCESS_KEY
            - name: APPFLOWY_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_S3_SECRET_KEY
            - name: APPFLOWY_MAILER_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_MAILER_SMTP_HOST
            - name: APPFLOWY_MAILER_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_MAILER_SMTP_PORT
            - name: APPFLOWY_MAILER_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_MAILER_SMTP_USERNAME
            - name: APPFLOWY_MAILER_SMTP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_MAILER_SMTP_EMAIL
            - name: APPFLOWY_MAILER_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_MAILER_SMTP_PASSWORD
            - name: APPFLOWY_MAILER_SMTP_TLS_KIND
              valueFrom:
                secretKeyRef:
                  name: appflowy-worker-secret
                  key: APPFLOWY_MAILER_SMTP_TLS_KIND